name: oguk-calibrate-dev
channels:
- PSLmodels
- conda-forge
dependencies:
- python>=3.7.7
- ipython
- setuptools
- mkl>=2020.2
- psutil
- scipy>=1.5.0
- pandas>=1.0.5
- matplotlib
# - ogusa -- comment out for now since OG-USA on GH too big, an no Conda package
- dask==2.30.0
- dask-core==2.30.0
- distributed==2.30.1
- paramtools>=0.15.0
- openpyxl
- sphinx>=3.1.2
- pip
- pytest>=6.0
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- requests
- xlwt
- statsmodels
- linearmodels
- rpy2
- black
- pre-commit
- pip:
  - jupyter-book>=0.8.0
  - cs-kit
  - cs2tc
  - pandas-datareader
  - git+https://github.com/PSLmodels/OG-USA.git
  - git+https://github.com/nikhilwoodruff/openfisca-core.git
  - git+https://github.com/nikhilwoodruff/frs.git
  - git+https://github.com/PSLmodels/openfisca-uk.git
  - git+https://github.com/PSLmodels/microdf.git
